CREATE TABLE `express_delivery_status_linked` (
  `exp_org_code` varchar(32) NOT NULL COMMENT '寄递企业代码',
  `user_type` varchar(1) NOT NULL DEFAULT '1' COMMENT '用户类型，1个人用户，2机构用户',
  `bill_number` varchar(35) NOT NULL COMMENT '快递单号',
  `user_sign` varchar(128) NOT NULL COMMENT '用户内码',
  `id_pseude_code` varchar(128) DEFAULT NULL COMMENT '个人用户实名身份伪码',
  `user_id` varchar(16) NOT NULL DEFAULT '' COMMENT '个人用户序列号',
  `org_code` varchar(10) NOT NULL DEFAULT '' COMMENT '机构用户企业代码',
  `social_code` varchar(20) NOT NULL DEFAULT '' COMMENT '机构用户统一社会信用代码',
  `staff_code` varchar(16) NOT NULL COMMENT '收派员编号',
  `check_date` datetime NOT NULL COMMENT '查验时间 YYYY-MM-DD HH:mm:ss',
  `check_method` varchar(2) NOT NULL COMMENT '查验方式，01首次面验，02凭证二维码，03短信验证码，04微信验证码，05有效身份证，06身份证识别设备，07NFC+SAM，08OCR识别，99协议客户',
  `province` varchar(32) NOT NULL COMMENT '省',
  `city` varchar(32) NOT NULL COMMENT '市',
  `county` varchar(32) NOT NULL COMMENT '区县',
  `IsReported` varchar(2) DEFAULT NULL COMMENT '是否已上报:0：未上报 1：已上报',
  `UserIDType` varchar(2) DEFAULT NULL COMMENT '有效身份证件类型',
  `UserIDNo` varchar(35) DEFAULT NULL COMMENT '有效身份证件号码',
  `createDate` datetime NOT NULL DEFAULT '2017-08-01 00:00:00' COMMENT '创建时间',
  `TaxRegNo` varchar(30) NOT NULL DEFAULT '' COMMENT '税务登记证号',
  `IsPublic` varchar(20) NOT NULL DEFAULT 'normal' COMMENT '公共版数据类型,默认值为normal',
  `UserUnifiedId` varchar(128) DEFAULT NULL COMMENT '用户统一标识',
  `UserCardValidityStartDate` varchar(8) DEFAULT NULL COMMENT '用户有效身份证件有效期开始时间',
  `UserCardValidityEndDate` varchar(8) DEFAULT NULL COMMENT '用户有效身份证件有效期结束时间',
  `StaffUnifiedId` varchar(128) DEFAULT NULL COMMENT '收派员统一标识',
  `StaffCardType` varchar(2) DEFAULT NULL COMMENT '收派员有效身份证件类型',
  `StaffCardID` varchar(35) DEFAULT NULL COMMENT '收派员有效身份证件号码',
  `StaffCardValidityStartDate` varchar(8) DEFAULT NULL COMMENT '收派员有效身份证件有效期开始时间',
  `StaffCardValidityEndDate` varchar(8) DEFAULT NULL COMMENT '收派员有效身份证件有效期结束时间',
  `Street` varchar(256) DEFAULT NULL COMMENT '详细地址',
  `SenderLatLng` varchar(31) DEFAULT '' COMMENT '寄件行为发生地的GPS经纬度',
  `InternalsType` varchar(2) DEFAULT '' COMMENT '内件类型',
  `InternalsName` varchar(32) DEFAULT '' COMMENT '内件名称',
  `InternalsAmount` int(8) DEFAULT NULL COMMENT '内件数量',
  `ReceiverPhone` varchar(32) DEFAULT '' COMMENT '收件人联系电话',
  `check_date_sign` bigint(20) DEFAULT '0' COMMENT '查验时间',
  `iddd` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`iddd`),
  KEY `index_exporgcode` (`exp_org_code`) USING BTREE,
  KEY `index_userid` (`user_id`) USING BTREE,
  KEY `index_county` (`county`) USING BTREE,
  KEY `index_city` (`city`) USING BTREE,
  KEY `index_province` (`province`) USING BTREE,
  KEY `INDEX_IDTYPE_IDNO02` (`exp_org_code`,`user_id`) USING BTREE,
  KEY `index_check_date_sign` (`check_date_sign`),
  KEY `idx_eds_orgcode_useridno_useridtype` (`exp_org_code`,`UserIDNo`,`UserIDType`),
  KEY `index_exp_county` (`exp_org_code`,`county`)
) ENGINE=InnoDB AUTO_INCREMENT=17614050 DEFAULT CHARSET=utf8 COMMENT='快件状态信息查验记录';




CREATE TABLE `express_delivery_status_unlinked` (
  `exp_org_code` varchar(32) NOT NULL COMMENT '寄递企业代码',
  `user_type` varchar(1) NOT NULL DEFAULT '1' COMMENT '用户类型，1个人用户，2机构用户',
  `bill_number` varchar(35) NOT NULL COMMENT '快递单号',
  `user_sign` varchar(128) NOT NULL COMMENT '用户内码',
  `id_pseude_code` varchar(128) DEFAULT NULL COMMENT '个人用户实名身份伪码',
  `user_id` varchar(16) NOT NULL DEFAULT '' COMMENT '个人用户序列号',
  `org_code` varchar(10) NOT NULL DEFAULT '' COMMENT '机构用户企业代码',
  `social_code` varchar(20) NOT NULL DEFAULT '' COMMENT '机构用户统一社会信用代码',
  `staff_code` varchar(16) NOT NULL COMMENT '收派员编号',
  `check_date` datetime NOT NULL COMMENT '查验时间 YYYY-MM-DD HH:mm:ss',
  `check_method` varchar(2) NOT NULL COMMENT '查验方式，01首次面验，02凭证二维码，03短信验证码，04微信验证码，05有效身份证，06身份证识别设备，07NFC+SAM，08OCR识别，99协议客户',
  `province` varchar(32) NOT NULL COMMENT '省',
  `city` varchar(32) NOT NULL COMMENT '市',
  `county` varchar(32) NOT NULL COMMENT '区县',
  `IsReported` varchar(2) DEFAULT NULL COMMENT '是否已上报:0：未上报 1：已上报',
  `UserIDType` varchar(2) DEFAULT NULL COMMENT '有效身份证件类型',
  `UserIDNo` varchar(35) DEFAULT NULL COMMENT '有效身份证件号码',
  `createDate` datetime NOT NULL DEFAULT '2017-08-01 00:00:00' COMMENT '创建时间',
  `TaxRegNo` varchar(30) NOT NULL DEFAULT '' COMMENT '税务登记证号',
  `IsPublic` varchar(20) NOT NULL DEFAULT 'normal' COMMENT '公共版数据类型,默认值为normal',
  `UserUnifiedId` varchar(128) DEFAULT NULL COMMENT '用户统一标识',
  `UserCardValidityStartDate` varchar(8) DEFAULT NULL COMMENT '用户有效身份证件有效期开始时间',
  `UserCardValidityEndDate` varchar(8) DEFAULT NULL COMMENT '用户有效身份证件有效期结束时间',
  `StaffUnifiedId` varchar(128) DEFAULT NULL COMMENT '收派员统一标识',
  `StaffCardType` varchar(2) DEFAULT NULL COMMENT '收派员有效身份证件类型',
  `StaffCardID` varchar(35) DEFAULT NULL COMMENT '收派员有效身份证件号码',
  `StaffCardValidityStartDate` varchar(8) DEFAULT NULL COMMENT '收派员有效身份证件有效期开始时间',
  `StaffCardValidityEndDate` varchar(8) DEFAULT NULL COMMENT '收派员有效身份证件有效期结束时间',
  `Street` varchar(256) DEFAULT NULL COMMENT '详细地址',
  `SenderLatLng` varchar(31) DEFAULT '' COMMENT '寄件行为发生地的GPS经纬度',
  `InternalsType` varchar(2) DEFAULT '' COMMENT '内件类型',
  `InternalsName` varchar(32) DEFAULT '' COMMENT '内件名称',
  `InternalsAmount` int(8) DEFAULT NULL COMMENT '内件数量',
  `ReceiverPhone` varchar(32) DEFAULT '' COMMENT '收件人联系电话',
  `check_date_sign` bigint(20) DEFAULT '0' COMMENT '查验时间',
  `iddd` bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`iddd`),
  KEY `index_exporgcode_un` (`exp_org_code`) USING BTREE,
  KEY `index_userid_un` (`user_id`) USING BTREE,
  KEY `index_county_un` (`county`) USING BTREE,
  KEY `index_city_un` (`city`) USING BTREE,
  KEY `index_province_un` (`province`) USING BTREE,
  KEY `INDEX_IDTYPE_IDNO02_un` (`exp_org_code`,`user_id`) USING BTREE,
  KEY `index_check_date_sign_un` (`check_date_sign`),
  KEY `idx_eds_orgcode_useridno_useridtype_un` (`exp_org_code`,`UserIDNo`,`UserIDType`),
  KEY `index_exp_county_un` (`exp_org_code`,`county`)
) ENGINE=InnoDB AUTO_INCREMENT=17614050 DEFAULT CHARSET=utf8 COMMENT='快件状态信息查验记录';





CREATE TABLE `express_delivery_status_lined` (
   `exp_org_code` varchar(32) NOT NULL,
   `user_type` varchar(1) NOT NULL DEFAULT '1',
   `user_sign` varchar(128) NOT NULL COMMENT '用户内码',
   `bill_number` varchar(35) NOT NULL,
   `id_pseude_code` varchar(128) DEFAULT NULL,
   `user_id` varchar(16) NOT NULL DEFAULT '',
   `org_code` varchar(10) NOT NULL DEFAULT '',
   `social_code` varchar(20) NOT NULL DEFAULT '',
   `staff_code` varchar(16) NOT NULL,
   `check_date` datetime NOT NULL,
   `check_method` varchar(2) NOT NULL,
   `province` varchar(32) NOT NULL,
   `city` varchar(32) NOT NULL,
   `county` varchar(32) NOT NULL,
   `IsReported` varchar(2) DEFAULT NULL,
   `UserIDType` varchar(2) DEFAULT NULL,
   `UserIDNo` varchar(35) DEFAULT NULL,
   `createDate` datetime NOT NULL DEFAULT '1980-01-01 00:00:00',
   `TaxRegNo` varchar(30) NOT NULL DEFAULT '',
   `IsPublic` varchar(20) NOT NULL DEFAULT 'normal',
   `UserUnifiedId` varchar(128) DEFAULT NULL,
   `UserCardValidityStartDate` varchar(8) DEFAULT NULL,
   `UserCardValidityEndDate` varchar(8) DEFAULT NULL,
   `StaffUnifiedId` varchar(128) DEFAULT NULL,
   `StaffCardType` varchar(2) DEFAULT NULL,
   `StaffCardID` varchar(35) DEFAULT NULL,
   `StaffCardValidityStartDate` varchar(8) DEFAULT NULL,
   `StaffCardValidityEndDate` varchar(8) DEFAULT NULL,
   `Street` varchar(256) DEFAULT '',
   `SenderLatLng` varchar(31) DEFAULT '',
   `InternalsType` varchar(2) DEFAULT '',
   `InternalsName` varchar(32) DEFAULT '',
   `InternalsAmount` int(8) DEFAULT NULL,
   `ReceiverPhone` varchar(32) DEFAULT '',
   `check_date_sign` bigint(20) DEFAULT '0',
    KEY `index_exporgcode_un` (`exp_org_code`) USING BTREE,
  KEY `index_userid` (`user_id`) USING BTREE,
  KEY `index_county` (`county`) USING BTREE,
  KEY `index_city` (`city`) USING BTREE,
  KEY `index_province` (`province`) USING BTREE,
  KEY `INDEX_IDTYPE_IDNO02` (`exp_org_code`,`user_id`) USING BTREE,
  KEY `index_check_date_sign` (`check_date_sign`),
  KEY `idx_eds_orgcode_useridno_useridtype` (`exp_org_code`,`UserIDNo`,`UserIDType`),
  KEY `index_exp_county` (`exp_org_code`,`county`)
 ) ENGINE=innodb DEFAULT CHARSET=utf8;



 CREATE TABLE `express_delivery_status_unlinked` (
   `exp_org_code` varchar(32) NOT NULL,
   `user_type` varchar(1) NOT NULL DEFAULT '1',
   `user_sign` varchar(128) NOT NULL COMMENT '用户内码',
   `bill_number` varchar(35) NOT NULL,
   `id_pseude_code` varchar(128) DEFAULT NULL,
   `user_id` varchar(16) NOT NULL DEFAULT '',
   `org_code` varchar(10) NOT NULL DEFAULT '',
   `social_code` varchar(20) NOT NULL DEFAULT '',
   `staff_code` varchar(16) NOT NULL,
   `check_date` datetime NOT NULL,
   `check_method` varchar(2) NOT NULL,
   `province` varchar(32) NOT NULL,
   `city` varchar(32) NOT NULL,
   `county` varchar(32) NOT NULL,
   `IsReported` varchar(2) DEFAULT NULL,
   `UserIDType` varchar(2) DEFAULT NULL,
   `UserIDNo` varchar(35) DEFAULT NULL,
   `createDate` datetime NOT NULL DEFAULT '1980-01-01 00:00:00',
   `TaxRegNo` varchar(30) NOT NULL DEFAULT '',
   `IsPublic` varchar(20) NOT NULL DEFAULT 'normal',
   `UserUnifiedId` varchar(128) DEFAULT NULL,
   `UserCardValidityStartDate` varchar(8) DEFAULT NULL,
   `UserCardValidityEndDate` varchar(8) DEFAULT NULL,
   `StaffUnifiedId` varchar(128) DEFAULT NULL,
   `StaffCardType` varchar(2) DEFAULT NULL,
   `StaffCardID` varchar(35) DEFAULT NULL,
   `StaffCardValidityStartDate` varchar(8) DEFAULT NULL,
   `StaffCardValidityEndDate` varchar(8) DEFAULT NULL,
   `Street` varchar(256) DEFAULT '',
   `SenderLatLng` varchar(31) DEFAULT '',
   `InternalsType` varchar(2) DEFAULT '',
   `InternalsName` varchar(32) DEFAULT '',
   `InternalsAmount` int(8) DEFAULT NULL,
   `ReceiverPhone` varchar(32) DEFAULT '',
   `check_date_sign` bigint(20) DEFAULT '0',
    KEY `index_exporgcode_un` (`exp_org_code`) USING BTREE,
  KEY `index_userid_un` (`user_id`) USING BTREE,
  KEY `index_county_un` (`county`) USING BTREE,
  KEY `index_city_un` (`city`) USING BTREE,
  KEY `index_province_un` (`province`) USING BTREE,
  KEY `INDEX_IDTYPE_IDNO02_un` (`exp_org_code`,`user_id`) USING BTREE,
  KEY `index_check_date_sign_un` (`check_date_sign`),
  KEY `idx_eds_orgcode_useridno_useridtype_un` (`exp_org_code`,`UserIDNo`,`UserIDType`),
  KEY `index_exp_county_un` (`exp_org_code`,`county`)
 ) ENGINE=innodb DEFAULT CHARSET=utf8;